In [1]:
from matplotlib import pyplot as plt

import seaborn as sns

from pylab import rcParams
rcParams['figure.figsize'] = (9,6)
import numpy as np


from sklearn import datasets

In [2]:
X, y = datasets.load_boston(return_X_y = True)

c:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the C

In [3]:
X.shape

(506, 13)

In [4]:
print(X)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [5]:
y.shape

(506,)

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [7]:
X_train.shape, X_test.shape

((404, 13), (102, 13))

Построение регрессии

In [8]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([ 9.29512326, 29.19765156, 30.79464184, 19.60602658, 20.59852279,
       17.14765796, 34.86025147,  4.839783  , 44.07239709, 31.91986214,
       32.8424835 , 35.22583919, 18.99158057, 10.61055276, 17.06681741,
       19.28031406, 18.33029125, 16.00410424, 17.22903317, 25.9863411 ,
       13.30756612, 22.53909525, 11.64388454, 23.38856283, 24.79570175,
       21.02052258, 26.15203508, 12.49031711, 15.56221531,  7.43199329,
       21.67450528, 32.88645584, 31.80726159, 13.20450871, 15.77093817,
       24.82635522, 25.28202945, 22.49461164, 22.92793013, 18.92443997,
        7.34974629, 34.58295506, 27.25856294, 15.47365315, 16.03577715,
       16.69060282, 33.74910563, 25.15562399, 15.90890292, 22.46368382,
       31.98662043, 17.11711966, 23.48482741, 12.78463745, 22.3782227 ,
       33.70760334, 16.38939552, 27.68356318, 13.00746036, 19.53529038,
       28.1012531 , 38.65600582, 17.95696261, 19.12864298, 16.23699754,
       38.26233924, 33.02875106, 30.93019098, 37.56392566, 20.77